### ISSUE TITLE
Username should not be used in repository path

### ISSUE THREAD

**Issue by meeDamian** [peter-evans/dockerhub-description#1]
As a user `X`, I can have push access to repository `Y/Z` on Docker Hub.

Currently it's impossible to interact with it.

Please change behaviour of `DOCKERHUB_REPOSITORY` to accept `<namespace>/<name>` format, so that doing the following is possible:

```yml
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v1.0.1
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        DOCKERHUB_REPOSITORY: ${GITHUB_REPOSITORY,,}
```

Thank you :).
