### ISSUE TITLE
Unable to access my repository

### ISSUE THREAD

**Issue by Randark-JMT** [peter-evans/dockerhub-description#110]
Thank you very much for writing this tool, but when I was using it I encountered some problems:
![图片](https://user-images.githubusercontent.com/56223739/216549361-4935c559-0702-4dcf-b74e-0b83745a0fe9.png)
I am not sure where the problem is coming from, so I created this issue. here is the code for my action:
```yml
name: Publish Docker image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: randark/nssctf-round_v7-shadowflag
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: RandarkJMT/NSSCTF-Round_v7-ShadowFlag
```
