### ISSUE TITLE
Updates readme but not description?

### ISSUE THREAD

**Issue by scyto** [peter-evans/dockerhub-description#17]
Nice piece of work, thank you for making this.

I get how this updated the readme on docker hub, that worked perfectly once I worked out I couldn't use the API token.
I am missing how this updates the docker hub description?  Aka this:

![image](https://user-images.githubusercontent.com/11369180/93730466-a1aa5580-fb7d-11ea-9063-1b83e36228e2.png)

**Comment by peter-evans** [comment]
Hi @scyto 

There are two "fields" in DockerHub, one is called `description` and the other is called `full_description`. This action currently only updates `full_description` based on the contents of a readme.md.

I didn't add a way to update the short `description` field because I didn't expect anyone to need that feature. Do you want to dynamically change the description based on events in GitHub? If the description is not going to change then I'm not sure if it makes sense to update it each time the action runs.

**Comment by scyto** [comment]
Hi, thanks for the reply.  This is more about CI using workflows.  I don't want to ever touch the docker hub by hand even for the first updated of description for any repo.  And yes I changed the description as I added different architectures. see https://hub.docker.com/repository/docker/scyto/infinitude - my next try will be to see if i can use 

I guess a noob at this what confused me is in the dockerhub UI the description is called description and full_description is called readme.  Which confused me wrt the name of the action :-)

After i logged this i found `christian-korneck/update-container-description-action@v1` which does both so i don't think it is critical for yours to support this and you can close if you wish (though i note yours is being recommended by docker in their docker-push-action action set!)

**Comment by peter-evans** [comment]
That's a very good point about not wanting to touch DockerHub at all for new repository setups. I think I'll add this to the action.

**Comment by scyto** [comment]
cool, i am happy to test it if you let me know

**Comment by peter-evans** [comment]
@scyto I took the opportunity to convert the action to Typescript, which I've been meaning to do for a while. At the same time I added the new input `short-description` where you can set a 100 character max string.

Inputs can now be set via `with` (`env` inputs still work for backwards compatibility)

```yml
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: user1/my-repo
        short-description: A short description of my Docker image
```
