### ISSUE TITLE
Step fails with no README file

### ISSUE THREAD

**Issue by tzurielweisberg** [peter-evans/dockerhub-description#202]
Hi, 
My action fails with 
ENOENT: no such file or directory, open './README.md'
Although the file exists.
Repo: https://github.com/tzurielweisberg/testing-docker-description

Job: https://github.com/tzurielweisberg/testing-docker-description/actions/runs/6008305397/job/16295739517

Action:

```
name: Send description

on:
  workflow_dispatch:

jobs:
  build:
    name: Send description
    runs-on: ubuntu-latest
    steps:
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PWD }}
        repository: ${{ secrets.DOCKER_REPO_NAME }}
```
