### ISSUE TITLE
Bug: Specifying README filepath gives `no such file or directory` error even when the file exists

### ISSUE THREAD

**Issue by EshaanAgg** [peter-evans/dockerhub-description#220]
I have recently integrated this GitHub action into the [`fedimint-ui`](https://github.com/fedimint/ui/) repository. I am using this action in [this workflow](https://github.com/fedimint/ui/actions/runs/6538845765/job/17755640451). The workflow is failing with the `ENOENT: no such file or directory, open './apps/gateway-ui/README.md'` error even though the same file clearly exists in the repository. Can please someone help me debugging the same?

![image](https://github.com/peter-evans/dockerhub-description/assets/96648934/990be42b-52cc-41f9-9ff0-3de7fabec832)

**Comment by peter-evans** [comment]
Hi @EshaanAgg 

Have you checked out the repository locally (on the runner) before executing this action? The file needs to be available locally, otherwise the action cannot find it.

```yml
    - uses: actions/checkout@v4

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: peterevans/dockerhub-description
```
https://github.com/peter-evans/dockerhub-description#usage
