### ISSUE TITLE
Doesn't work if username and repository namespace is equal

### ISSUE THREAD

**Issue by RouHim** [peter-evans/dockerhub-description#37]
Hey guys,
first thank you for this awesome project.
I've got the following problem:

My github action workflow configuration:
```
  - name: Update docker hub description
    uses: peter-evans/dockerhub-description@v2
    with:
      username: ${{ secrets.DOCKERHUB_USERNAME }} # --> rouhim
      password: ${{ secrets.DOCKERHUB_PASSWORD }}
      repository: rouhim/beammp-docker   # ---> gets replaced ***/beammp-docker
```

The output:
```
Run peter-evans/dockerhub-description@v2
  with:
    username: ***
    password: ***
    repository: ***/beammp-docker
Acquiring token
Sending PATCH request
Error: NOT FOUND
```

My best guess is that the github action replaces and breaks the repository path, because my github repository contains my dockerhub username.

---

Full github action setup: https://github.com/RouHim/beammp-docker/blob/main/.github/workflows/main.yml
According docherhub repo: https://hub.docker.com/r/rouhim/beammp-server
