### ISSUE TITLE
Feature Request - Pull Short Description from GitHub Description

### ISSUE THREAD

**Issue by computeronix** [peter-evans/dockerhub-description#38]
In the action you allow for short-description to be passed.

Could you allow this option to be set to true which would then take the GitHub Repro Description and sync that to the Docker Hub Description?

**Comment by peter-evans** [comment]
Hi @computeronix 

You can do this already by setting the input with the event context.

```yml
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: peterevans/dockerhub-description
        short-description: ${{ github.event.repository.description }}
```
I will update the readme to add this to the examples.
