### ISSUE TITLE
Warning: empty string in mask + Error: unauthorized

### ISSUE THREAD

**Issue by akloeckner** [peter-evans/dockerhub-description#42]
I've started using your action in my workflow:
https://github.com/akloeckner/TileBoard-docker-nightly/actions/runs/805068712

Thanks a lot!

I trigger the workflow on a `schedule` and use nothing special in it as far as I can see:
```yaml
    - name: Check out code
      uses: actions/checkout@v2
    - name: Update Docker Hub description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: akloeckner/tileboard
        short-description: ${{ github.event.repository.description }}
```

It gives me the following error message:
```
Run peter-evans/dockerhub-description@v2
  with:
    username: ***
    password: ***
    repository: ***/tileboard
    short-description: Nightly builds of Tileboard
Acquiring token
Warning: Can't add secret mask for empty string in ##[add-mask] command.
Sending PATCH request
Error: Unauthorized
```

The error is not reproducible to me, since it sometimes runs through and sometimes gives the error above. If I then "re-run all jobs", it works as expected. Also, when I start the workflow manually, I has worked all the time so far.

Do you have any idea, what could cause this?
