### ISSUE TITLE
File size exceeds the maximum allowed 25000 bytes

### ISSUE THREAD

**Issue by orhun** [peter-evans/dockerhub-description#69]
Hello,

I have a README.md file of 39k and I can't upload it due to size limit. I'm using `dockerhub-description` action as follows:

```yml
      - name: Update Docker Hub description
        if: github.event_name != 'pull_request'
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
```

Related run: https://github.com/orhun/git-cliff/runs/7540171483
